name: release-and-publish
"on":
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
permissions:
  contents: read
jobs:
  setup_variables:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    outputs:
      isLatest: ${{ steps.release_type.outputs.latest }}
    steps:
      - id: release_type
        name: Identify release type
        run: echo "::set-output name=latest::$LATEST"
        env:
          LATEST: >-
            ${{ contains(github.ref, '-next') != true && contains(github.ref,
            '-rc') != true }}
  create_release:
    permissions:
      contents: write
    needs:
      - setup_variables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Create release for tag
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          tag_name: ${{ github.ref }}
          body: >-
            Please refer to
            [CHANGELOG.md](https://github.com/kulshekhar/ts-jest/blob/main/CHANGELOG.md)
            for details.
          draft: false
          prerelease: ${{ needs.setup_variables.outputs.isLatest != 'true' }}
          token: ${{ secrets.GITHUB_TOKEN }}
  publish_to_npm:
    needs:
      - setup_variables
      - create_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
      - name: Check lock file
        run: npm ci
      - name: Publish with latest tag
        if: ${{ needs.setup_variables.outputs.isLatest == 'true' }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish with next tag
        if: ${{ needs.setup_variables.outputs.isLatest != 'true' }}
        run: npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
